<?php

namespace Ruon\Data;

/**
 * Test class for DataRepositoryAbstract.
 * Generated by PHPUnit on 2012-04-29 at 12:38:09.
 */
class DataRepositoryAbstractTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var DataRepositoryAbstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this->object = $this->getMockForAbstractClass(
			'Ruon\\Data\\DataRepositoryAbstract'
		);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{

	}

    /**
     * @covers Ruon\Data\DataRepositoryAbstract::flushSet
     */
	public function testFlushSet()
	{
		$test = array('a' => 'b');

		$this->object
			->expects($this->once())
			->method('flush')
			->with();

		$this->object
			->expects($this->once())
			->method('mset')
			->with($test);

		$this->object->flushSet($test);
	}

}
