<?php

namespace Ruon\Di\Injector;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-17 at 23:33:05.
 */
class InjectorStandartTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InjectorStandart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InjectorStandart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Ruon\Di\Injector\InjectorStandart::getAnnotationValue
     * @todo   Implement testGetAnnotationValue().
     */
    public function testGetAnnotationValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ruon\Di\Injector\InjectorStandart::inject
     * @todo   Implement testInject().
     */
    public function testInject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
