<?php

namespace Ruon\Loader;

/**
 * Test class for LoaderAbstract.
 * Generated by PHPUnit on 2012-04-19 at 18:43:01.
 */
class LoaderAbstractTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var LoaderAbstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = $this->getMockForAbstractClass(
			'Ruon\\Loader\\LoaderAbstract'
		);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers Ruon\Loader\LoaderAbstract::setPath
	 * @covers Ruon\Loader\LoaderAbstract::getPaths
	 */
	public function testSetPath()
	{
		$originalPaths = $this->object->getPaths();

		$this->object->setPath(
			'Ruon',
			__DIR__ . '/../'
		);
		$paths = $this->object->getPaths();
		$this->assertEquals(
			array(
				'Ruon' => __DIR__ . '/../'
			),
			$paths
		);

		$this->object->setPaths($originalPaths);
	}

	/**
	 * @covers Ruon\Loader\LoaderAbstract::setPaths
	 * @covers Ruon\Loader\LoaderAbstract::getPaths
	 */
	public function testSetPaths()
	{
        $tester = new \Ruon\Lib\Test\Setter;
        $tester->test(
            $this,
            $this->object,
            'Paths',
            array(
                array(),
                array('a' => 'b')
            )
        );
	}

}
