<?php

namespace Ruon\Annotation;

require_once __DIR__ . '/../../Annotation/AnnotationSet.php';

/**
 * Test class for AnnotationSet.
 * Generated by PHPUnit on 2012-09-18 at 17:44:49.
 */
class AnnotationSetTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers Ruon\Annotation\AnnotationSet::__construct
	 * @covers Ruon\Annotation\AnnotationSet::get
	 * @covers Ruon\Annotation\AnnotationSet::set
	 */
	public function testGetSet()
	{
		$data = array('key' => 'value');
		$mock = $this->getMock(
			'AnnotationRow', array('__construct', 'get', 'set'), array($data)
		);
		$set = new AnnotationSet($mock, array(), array());
		$mock
			->expects($this->once())
			->method('set')
			->with($this->equalTo('key'), $this->equalTo('value'));
		$set->set('key', 'value');
		$mock
			->expects($this->once())
			->method('get')
			->with($this->equalTo('key'));
		$a = $set->get('key');
		unset($a);
	}

	/**
	 * @covers Ruon\Annotation\AnnotationSet::getMethod
	 * @covers Ruon\Annotation\AnnotationSet::setMethod
	 */
	public function testGetSetMethod ()
	{
		$data = array('key' => 'value');
		$mock = $this->getMock(
			'AnnotationRow', array('__construct', 'get', 'set'), array($data)
		);
		$methods = array('key' => 'value');
		$set = new AnnotationSet($mock, $methods, array());
		$this->assertEquals('value', $set->getMethod('key'));
		$set->setMethod('key', 'otherValue');
		$this->assertEquals('otherValue', $set->getMethod('key'));
	}

	/**
	 * @covers Ruon\Annotation\AnnotationSet::getProperty
	 * @covers Ruon\Annotation\AnnotationSet::setProperty
	 */
	public function testGetSetProperty ()
	{
		$data = array('key' => 'value');
		$mock = $this->getMock(
			'AnnotationRow', array('__construct', 'get', 'set'), array($data)
		);
		$properties = array('key' => 'value');
		$set = new AnnotationSet($mock, array(), $properties);
		$this->assertEquals('value', $set->getProperty('key'));
		$set->setProperty('key', 'otherValue');
		$this->assertEquals('otherValue', $set->getProperty('key'));
	}
}