<?php

namespace Ruon\Annotation;

/**
 * Test class for AnnotationRow.
 * Generated by PHPUnit on 2012-09-18 at 17:36:58.
 */
class AnnotationRowTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers Ruon\Annotation\AnnotationRow::get
	 * @covers Ruon\Annotation\AnnotationRow::set
	 * @covers Ruon\Annotation\AnnotationRow::__construct
	 */
	public function testGetSet()
	{
		$data = array();
		$data['key'] = $this->getMock('Annotation');
		$row = new AnnotationRow($data);
		$otherMock = $this->getMock('Annotation');
		$this->assertSame($data['key'], $row->get('key'));
		$row->set('otherKey', $otherMock);
		$this->assertSame($otherMock, $row->get('otherKey'));
	}
}