<?php

namespace Ruon\Annotation;

require_once __DIR__ . '/../../Annotation/AnnotationSourceAbstract.php';

/**
 * Test class for AnnotationSourceAbstract.
 * Generated by PHPUnit on 2012-09-18 at 18:13:36.
 */
class AnnotationSourceAbstractTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{

	}

	/**
	 * @covers Ruon\Annotation\AnnotationSourceAbstract::get
	 */
	public function testGet ()
	{
		$mock = $this->getMockForAbstractClass(
			'Ruon\\Annotation\\AnnotationSourceAbstract',
			array(),
			'',
			true,
			true,
			true,
			array(
				'getClass', 'getMethods', 'getProperties'
			)
		);
		$class = $this->getMock('\\StdClass');
		$result = $mock->get($class);
		$this->assertInstanceOf(
			'Ruon\\Annotation\\AnnotationSet', $result
		);
	}
}