<?php

namespace Ruon\Core\Annotation;

require_once dirname (__FILE__) . '/../../../Core/Annotation/Annotation.php';

/**
 * Test class for Annotation.
 * Generated by PHPUnit on 2012-09-18 at 17:25:29.
 */
class AnnotationTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{

	}

	/**
	 * @covers \Ruon\Core\Annotation\Annotation::__construct
	 * @covers \Ruon\Core\Annotation\Annotation::__get
	 * @covers \Ruon\Core\Annotation\Annotation::__set
	 * @covers \Ruon\Core\Annotation\Annotation::getName
	 */
	public function testGetSet()
	{
		$data = array(
			'key1'	=> 'value1',
			'key2'	=> array(
				'key21'	=> 'value2.1',
				'key22'	=> 'value2.2',
				'key23'	=> array(
					'key231'	=> 'value3.3.1'
				)
			)
		);
		$annotation = new Annotation('test', $data);
		$this->assertEquals('test', $annotation->getName());
		$this->assertEquals('value1', $annotation->key1);
		$annotation->key1 = 'value1new';
		$this->assertEquals('value1new', $annotation->key1);
		$this->assertEquals('value2.1', $annotation->key2->key21);
		$this->assertEquals('value3.3.1', $annotation->key2->key23->key231);
	}
}