<?php

namespace Ruon\Core\DependencyInjection\Injector;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-06 at 22:12:40.
 */
class InjectorAbstractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InjectorAbstract
     */
    protected $stub;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->stub = $this->getMockForAbstractClass(
            __NAMESPACE__ . '\\InjectorAbstract'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Ruon\Core\DependencyInjection\Injector\InjectorAbstract::getInstanceSource
     * @covers Ruon\Core\DependencyInjection\Injector\InjectorAbstract::setInstanceSource
     */
    public function testSetInstanceSource()
    {
        $tester = new \Ruon\Lib\Test\Setter();
        $tester->test($this, $this->stub, 'InstanceSource');
    }

    /**
     * @covers Ruon\Core\DependencyInjection\Injector\InjectorAbstract::getServiceSource
     * @covers Ruon\Core\DependencyInjection\Injector\InjectorAbstract::setServiceSource
     */
    public function testSetServiceSource()
    {
        $tester = new \Ruon\Lib\Test\Setter();
        $tester->test($this, $this->stub, 'ServiceSource');
    }

}
