<?php

namespace Ruon\Core\Loader;

/**
 * Test class for LoaderAutoloadAbstract.
 * Generated by PHPUnit on 2012-04-24 at 10:13:58.
 */
class LoaderAutoloadAbstractTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Loader_LoaderAutoloadAbstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = $this->getMockForAbstractClass('Ruon\\Core\\Loader\\LoaderAutoloadAbstract');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers Ruon\Core\Loader\LoaderAutoloadAbstract::register
	 */
	public function testRegister()
	{
		$this->assertTrue($this->object->register());
	}

	/**
	 * @covers Ruon\Core\Loader\LoaderAutoloadAbstract::unregister
	 */
	public function testUnregister()
	{
		$this->assertTrue($this->object->unregister());
	}

}

